import { Button, LineEdit, ComboBox } from "std-widgets.slint";
import { CregSignUpWindow } from "Creg8_Sign_Up.slint";

export component Creg8-Window inherits Window {
    preferred-width: 800px;
    preferred-height: 730px;
    title: "University Course Registration System - Group 8";
    background: #aaDCe6;

    SignupWindow := CregSignUpWindow{
        width: parent.width * 80%;
        height: parent.height * 95%;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    VerticalLayout {
        padding: 12px;
        spacing: 6px;

        Text{
            text: "Welcome to the Course Registration Portal";
            font-size: 30px;
            font-weight: 800;
            color: black;
            horizontal-alignment: center;
        }

        RSU-logo := Rectangle {
            Image {
                source: @image-url("../../../resources/rsu_logo.jpg");
                width: 100%;
                height: parent.height * 40%;
                horizontal-alignment: center;
            }
        }

        UserNameRow := HorizontalLayout{
            Text {text: "Username:"; font-size: 24px; color: black; font-weight: 650;}
            LineEdit {
                placeholder-text:  "Enter your username";
                font-size: 24px;
            }
        }

        UniRow := HorizontalLayout{
            Text {text: "University:"; font-size: 24px; color: black; font-weight: 650;}
            ComboBox {
                model: ["Rivers State University", "University of Port Harcourt", "Ignatius Ajuru"];
                current-value: "Rivers State University";

            }
        }

        PasswordRow := HorizontalLayout{
            Text {text: "Password:"; font-size: 24px; color: black; font-weight: 650;}
            LineEdit {
                placeholder-text:  "Enter your password";
                font-size: 24px;
                input-type: password;
            }
        }

        HorizontalLayout {
            height: parent.height / 12;
            padding: 0px;
            spacing: 8px;

            log := Rectangle {
                logText := Text {vertical-alignment: center; color: black;}
                logTouch := TouchArea{}
                border-color: black;
                border-radius: 50px;
                border-width: 1px;
                states [
                    not-hovering when !logTouch.has-hover && !logTouch.pressed: {
                        logText.text: "Log In";
                        logText.font-size: 24px;
                    }
                    hovering-but-not-click when logTouch.has-hover && !logTouch.pressed: {
                        logText.text: "You want to Log In?";
                        logText.font-size: 20px;
                    }
                    clicked-the-button when logTouch.pressed: {
                        log.background: gray;
                        out { animate log.background { duration: 1000ms;}}
                        logText.text: "You want to Log In?";
                        logText.font-size: 20px;
                    }
                ]
            }
            sig := Rectangle {
                sigText := Text {vertical-alignment: center; color: black;}
                sigTouch := TouchArea{clicked => { SignupWindow.show();}}

                border-color: black;
                border-radius: 50px;
                border-width: 1px;
                states [
                    not-hovering when !sigTouch.has-hover && !sigTouch.pressed: {
                        sigText.text: "Sign Up";
                        sigText.font-size: 24px;
                    }
                    hovering-but-not-click when sigTouch.has-hover && !sigTouch.pressed: {
                        //sig.background: #afDCe6;
                        sigText.text: "You want to Sign Up?";
                        sigText.font-size: 20px;
                    }
                    clicked-the-button when sigTouch.pressed: {
                        sig.background: gray;
                        out { animate sig.background { duration: 1000ms;}}
                        sigText.text: "You want to Sign Up?";
                        sigText.font-size: 20px;
                    }
                ]
            }
        }

    }
}